language: go

go:
  - 1.7
  - 1.8
  - master

matrix:
  allow_failures:
  - go: master

sudo: false

services:
  - docker

install:
  - make setup-ci

before_script:
  - make run-containers
  - make create-es-index-template

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
  - curl -XPOST "$TEST_FARM_URL"
